// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { AuthProvider } from "./auth/cotexts/AuthContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <AuthProvider>{children}</AuthProvider>
//       </body>
//     </html>
//   );
// }



import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./auth/cotexts/AuthContext";
import localFont from 'next/font/local'
import Script from 'next/script'
import { Toaster } from '@/components/ui/sonner';
import DesktopNavigation from "./website-navigation/components/DesktopNavigation";
import Navigation from "./website-navigation/components/Navigation";

const gilroyRegular = localFont({
  src: '../public/fonts/gillroy/Gilroy-Regular.ttf',
  variable: '--font-gilroy-regular',
  display: 'swap',
  preload: true,
})

const gilroyBold = localFont({
  src: '../public/fonts/gillroy/Gilroy-Bold.ttf',
  variable: '--font-gilroy-bold',
  display: 'swap',
  preload: true,
})

const gilroySemiBold = localFont({
  src: '../public/fonts/gillroy/Gilroy-SemiBold.ttf',
  variable: '--font-gilroy-semibold',
  display: 'swap',
  preload: true,
})

const gilroyMedium = localFont({
  src: '../public/fonts/gillroy/Gilroy-Medium.ttf',
  variable: '--font-gilroy-medium',
  display: 'swap',
  preload: true,
})

const gilroyExtraBold = localFont({
  src: '../public/fonts/gillroy/Gilroy-ExtraBold.ttf',
  variable: '--font-gilroy-extrabold',
  display: 'swap',
  preload: true,
})

const gilroyBlack = localFont({
  src: '../public/fonts/gillroy/Gilroy-Black.ttf',
  variable: '--font-gilroy-black',
  display: 'swap',
  preload: true,
})

const gilroyLight = localFont({
  src: '../public/fonts/gillroy/Gilroy-Light.ttf',
  variable: '--font-gilroy-light',
  display: 'swap',
  preload: true,
})

const gilroyHeavy = localFont({
  src: '../public/fonts/gillroy/Gilroy-Heavy.ttf',
  variable: '--font-gilroy-heavy',
  display: 'swap',
  preload: true,
})

export const metadata: Metadata = {
  title: "Fraterny - Social Network for Developers",
  description: "Join Fraterny, the professional social network for developers. Connect, collaborate, and grow with fellow software engineers worldwide.",
  keywords: "developers network, software engineering community, professional networking, tech collaboration, coding community",
  
  authors: [{ name: "Fraterny" }],
  creator: "Fraterny",
  publisher: "Fraterny",
  
  metadataBase: new URL('https://fraterny.in'), // Replace with your actual domain
  
  alternates: {
    canonical: '/',
  },
  
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  
  openGraph: {
    title: "Fraterny - Social Network for Developers",
    description: "Join Fraterny, the professional social network for developers. Connect, collaborate, and grow with fellow software engineers worldwide.",
    type: "website",
    locale: "en_US",
    url: '/',
    siteName: "Fraterny",
    images: [
      {
        url: '/favicon-32x32.png', // Place your OG image in public folder
        width: 1200,
        height: 630,
        alt: 'Fraterny - Social Network for Developers',
      },
    ],
  },
  
  twitter: {
    card: "summary_large_image",
    title: "Fraterny - Social Network for Developers",
    description: "Join Fraterny, the professional social network for developers. Connect, collaborate, and grow with fellow software engineers worldwide.",
    images: ['/favicon-32x32.png'], // Place your Twitter image in public folder
    creator: '@fraterny', // Add your Twitter handle
  },
  
  verification: {
    google: 'your-google-verification-code', // Add after verifying in Google Search Console
    // yandex: 'your-yandex-verification-code',
    // other: 'your-other-verification-code',
  },
  
  icons: {
    icon: [
      { url: '/favicon-32x32.png' },
      { url: '/favicon-32x32.png', type: 'image/png', sizes: '32x32' },
    ],
    apple: [
      { url: '/favicon-32x32.png' },
    ],
    shortcut: '/favicon.ico',
  },
  
  manifest: '/manifest.json',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: 'Fraterny',
    description: 'Professional social network for developers',
    url: 'https://fraterny.in',
    potentialAction: {
      '@type': 'SearchAction',
      target: {
        '@type': 'EntryPoint',
        urlTemplate: 'https://fraterny.in/search?q={search_term_string}',
      },
      'query-input': 'required name=search_term_string',
    },
    sameAs: [
      'https://twitter.com/fraterny',
      'https://linkedin.com/company/fraterny',
      'https://github.com/fraterny',
    ],
  };

  const organizationJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Fraterny',
    description: 'Social Network for Developers',
    url: 'https://fraterny.in',
    logo: 'https://fraterny.in/logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      email: 'contact@fraterny.in',
      contactType: 'Customer Service',
    },
    sameAs: [
      'https://twitter.com/fraterny',
      'https://linkedin.com/company/fraterny',
      'https://github.com/fraterny',
    ],
  };



  return (
    <html lang="en">
      <head>
        {/* Preload hero images for faster LCP */}
        <link
          rel="preload"
          as="image"
          href="/hero-desktop.webp"
          media="(min-width: 641px)"
          fetchPriority="high"
        />
        <link
          rel="preload"
          as="image"
          href="/hero-mobile.webp"
          media="(max-width: 640px)"
          fetchPriority="high"
        />
        <Script
          id="website-jsonld"
          type="application/ld+json"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <Script
          id="organization-jsonld"
          type="application/ld+json"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
      {/* Defer all analytics to lazyOnload for better performance */}
      <Script
        strategy="lazyOnload">
        {`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-MPD3F25K');`}
      </Script>
      <Script
        src="https://www.googletagmanager.com/gtag/js?id=G-FXY9X6KYTZ"
        strategy="lazyOnload"
      />
      
      <Script id="google-analytics" strategy="lazyOnload">
        {`window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-FXY9X6KYTZ', {
            send_page_view: false
          });`}
      </Script>

      <Script id="meta-pixel" strategy="lazyOnload">
        {`
          !function(f,b,e,v,n,t,s)
          {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
          n.callMethod.apply(n,arguments):n.queue.push(arguments)};
          if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
          n.queue=[];t=b.createElement(e);t.async=!0;
          t.src=v;s=b.getElementsByTagName(e)[0];
          s.parentNode.insertBefore(t,s)}(window, document,'script',
          'https://connect.facebook.net/en_US/fbevents.js');
          fbq('init', '24279099175074291');
          fbq('track', 'PageView', {}, {
            eventID: 'pageview_' + Date.now() + '_' + Math.random().toString(36).substring(2, 9)
          });
        `}
      </Script>

      <Script id="reddit-pixel" strategy="lazyOnload">
        {`
          !function(w,d){if(!w.rdt){var p=w.rdt=function(){p.sendEvent?p.sendEvent.apply(p,arguments):p.callQueue.push(arguments)};p.callQueue=[];var t=d.createElement("script");t.src="https://www.redditstatic.com/ads/pixel.js",t.async=!0;var s=d.getElementsByTagName("script")[0];s.parentNode.insertBefore(t,s)}}(window,document);
          rdt('init','a2_hq9z7unfvynl', {
            optOut: false,
            useDecimalCurrencyValues: true
          });
          rdt('track', 'PageVisit');
        `}
      </Script>
      </head>
      <body
        style={{ backgroundColor: '#f9fafb', minHeight: '100vh' }}
        className={`
          bg-gray-50
          ${gilroyRegular.variable}
          ${gilroyBold.variable}
          ${gilroySemiBold.variable}
          ${gilroyMedium.variable}
          ${gilroyExtraBold.variable}
          ${gilroyBlack.variable}
          ${gilroyLight.variable}
          ${gilroyHeavy.variable}
        `}
      >
      <noscript>
        <img height="1" width="1" style={{display: 'none'}}
          src="https://www.facebook.com/tr?id=24279099175074291&ev=PageView&noscript=1"
        />
      </noscript>
      <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MPD3F25K"
          height="0" width="0" style={{display: 'none', visibility: 'hidden'}}>
        </iframe>
      </noscript>
      
      <div className="">
        <AuthProvider>
          <Toaster position="top-right" />
          {children}
        </AuthProvider>
      </div>
      </body>
    </html>
  );
}